# Generated by Django 3.2.15 on 2022-09-20 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="images",
            options={"verbose_name": "Images", "verbose_name_plural": "Images"},
        ),
    ]
