# Generated by Django 3.2.15 on 2022-10-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0002_alter_images_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="partners/%Y/%m"),
        ),
        migrations.AlterField(
            model_name="partner",
            name="date_created",
            field=models.DateField(),
        ),
    ]
