# Generated by Django 3.2.15 on 2022-10-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0004_auto_20221002_1205"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
