version: "3.7"
services:
  web:
    build: .
    container_name: bdeliv-api
    restart: unless-stopped
    volumes:
      - .:/code
      - ./gunicorn/logs:/gunicorn/logs
      - static:/code/static
      - media:/code/media

  nginx:
    restart: always
    build: ./nginx
    container_name: bdeliv-api-webserver
    volumes:
      - ./nginx/:/etc/nginx/conf.d
      - ./nginx/logs/:/code/logs
      - static:/code/static
      - media:/code/media
    ports:
      - "8000:80"
    depends_on:
      - web
    links:
      - web

volumes:
  media:
  static:
