# Generated by Django 3.2.15 on 2022-10-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=36)),
                (
                    "charge",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=9),
                ),
                ("vehicle_type", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="DistanceCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "charge",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=9),
                ),
            ],
        ),
    ]
