# Generated by Django 3.2.15 on 2022-11-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProximityRadius",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("radius", models.IntegerField(default=10)),
            ],
        ),
    ]
