# Generated by Django 3.2.15 on 2023-01-13 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0002_proximityradius"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="proximityradius",
            options={"verbose_name_plural": "Proximity Radius"},
        ),
    ]
