# Generated by Django 3.2.15 on 2022-09-16 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reg_number", models.CharField(max_length=10)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            (1, "Motorbike"),
                            (2, "Vehicle"),
                            (3, "Van"),
                            (4, "Truck"),
                        ],
                        default=1,
                        max_length=1,
                    ),
                ),
                ("model", models.CharField(blank=True, max_length=45, null=True)),
                ("color", models.CharField(blank=True, max_length=45, null=True)),
                ("insurance_expiry", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
