# Generated by Django 3.2.15 on 2023-03-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('1', 'Motorbike'), ('2', 'Vehicle'), ('3', 'Van'), ('4', 'Truck')], default=1, max_length=1),
        ),
    ]
