# Generated by Django 3.2.15 on 2023-01-13 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_onlinedrivers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="onlinedrivers",
            options={"verbose_name_plural": "Online Drivers"},
        ),
        migrations.AlterModelOptions(
            name="peopleonline",
            options={"verbose_name_plural": "People Online"},
        ),
    ]
