# Generated by Django 3.2.15 on 2023-06-28 08:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20230113_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinedrivers',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlinedrivers',
            name='date_deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlinedrivers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='onlinedrivers',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
