# Generated by Django 3.2.15 on 2022-10-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    (1, "created"),
                    (2, "confirmed"),
                    (3, "picked"),
                    (4, "transit"),
                    (5, "arrived"),
                ],
                default=1,
                max_length=1,
            ),
        ),
    ]
