# Generated by Django 3.2.15 on 2022-10-23 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookings", "0004_alter_receiverdetails_booking"),
        ("payments", "0003_earnings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=9),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (1, "created"),
                            (2, "confirmed"),
                            (3, "picked"),
                            (4, "transit"),
                            (5, "arrived"),
                        ],
                        default=1,
                        max_length=1,
                    ),
                ),
                ("transaction_id", models.CharField(max_length=108)),
                ("card_code", models.CharField(max_length=108)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_booking",
                        to="bookings.bookings",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
