# Generated by Django 3.2.15 on 2022-10-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="card_number",
            field=models.CharField(default="00000000", max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="expiration_date",
            field=models.CharField(default="12/2022", max_length=27),
            preserve_default=False,
        ),
    ]
