# Generated by Django 3.2.15 on 2022-10-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_auto_20221023_1742"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="booking",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="card_number",
        ),
        migrations.AddField(
            model_name="payment",
            name="order_id",
            field=models.CharField(blank=True, max_length=108, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="card_code",
            field=models.CharField(blank=True, max_length=108, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=108, null=True),
        ),
    ]
