# Generated by Django 3.2.15 on 2022-11-01 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_driverbankinginformation_requestearnings"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestearnings",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.order",
            ),
        ),
        migrations.AddField(
            model_name="requestearnings",
            name="status",
            field=models.CharField(
                choices=[(1, "Pending"), (2, "Paid")], default=1, max_length=1
            ),
        ),
    ]
