# Generated by Django 3.2.15 on 2022-11-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_auto_20221101_1515"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
