# Generated by Django 3.2.15 on 2022-11-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0011_alter_payment_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverbankinginformation",
            name="account_number",
            field=models.BigIntegerField(null=True),
        ),
    ]
