# Generated by Django 3.2.15 on 2022-12-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0014_alter_requestearnings_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestearnings",
            name="status",
            field=models.CharField(
                choices=[(1, "Pending"), (2, "Paid")], default=1, max_length=1
            ),
        ),
    ]
