# Generated by Django 3.2.15 on 2023-02-08 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_owner'),
        ('payments', '0015_alter_requestearnings_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='earnings',
            options={'verbose_name_plural': 'Earnings'},
        ),
        migrations.AlterModelOptions(
            name='requestearnings',
            options={'verbose_name_plural': 'Request Earnings'},
        ),
        migrations.AddField(
            model_name='order',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_vehicle', to='vehicles.vehicle'),
        ),
    ]
