# Generated by Django 3.2.15 on 2023-03-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_auto_20230208_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'created'), ('2', 'confirmed'), ('3', 'picked'), ('4', 'transit'), ('5', 'arrived')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('1', 'created'), ('2', 'confirmed'), ('3', 'picked'), ('4', 'transit'), ('5', 'arrived')], default=1, max_length=1),
        ),
    ]
