# Generated by Django 3.2.15 on 2023-06-13 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_auto_20230614_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiration_date',
            field=models.CharField(blank=True, max_length=27, null=True),
        ),
    ]
