# Generated by Django 3.2.15 on 2023-01-13 21:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phonenumber",
                    models.CharField(
                        max_length=17,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format +254700000000. Up to 14 digits allowed.",
                                regex="^\\+?1?\\d{9,10}$",
                            )
                        ],
                    ),
                ),
                ("otp", models.CharField(blank=True, max_length=9, null=True)),
                (
                    "count",
                    models.IntegerField(default=0, help_text="Number of otp_sent"),
                ),
                (
                    "is_validated",
                    models.BooleanField(
                        default=False,
                        help_text="If it is true, that means user have validate otp correctly in second API",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
