# Generated by Django 3.2.15 on 2023-06-26 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customotp',
            name='is_validated',
            field=models.BooleanField(default=False, help_text='If it is true, that means user has validated otp correctly in second API'),
        ),
        migrations.CreateModel(
            name='PreassignedOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('phonenumber', models.CharField(max_length=17, null=True)),
                ('otp', models.CharField(blank=True, max_length=9, null=True)),
                ('is_validated', models.BooleanField(default=False, help_text='If it is true, that means user has validated otp correctly in second API')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
