from django.urls import path

from .views import (
    UsersApiView,
    UserDeleteApiView,
    UserUpdateApiView,
    UpdateUserPassword,
    ProfileApiView,
    VehicleApiView,
    ProfileUpdateApiView,
    VehicleUpdateApiView,
    OrderApiView,
    OrderUpdateApiView,
    PaymentUpdateApiView,
    PaymentApiView,
    EarningsUpdateApiView,
    EarningsApiView,
    GetEarningsRequestApiView,
    EarningsRequestApiView,
    BookingsApiView,
    BookingDeleteApiView,
    BookingUpdateApiView,
    AdminDriverBankingInformationApiView,
    DriverRatingsApiView,
    DriverRatingsRanking,
)

urlpatterns = [
    path("api/users/", UsersApiView.as_view()),
    path("api/user/delete/", UserDeleteApiView.as_view()),
    path("api/user/update/", UserUpdateApiView.as_view()),
    path("api/user/update/password/", UpdateUserPassword.as_view()),
    path("api/profiles/", ProfileApiView.as_view()),
    path("api/update/profile/", ProfileUpdateApiView.as_view()),
    path("api/vehicles/", VehicleApiView.as_view()),
    path("api/vehicle/update/", VehicleUpdateApiView.as_view()),
    path("api/orders/", OrderApiView.as_view()),
    path("api/order/update/", OrderUpdateApiView.as_view()),
    path("api/payments/", PaymentApiView.as_view()),
    path("api/payment/update/", PaymentUpdateApiView.as_view()),
    path("api/earnings/", EarningsApiView.as_view()),
    path("api/earning/update/", EarningsUpdateApiView.as_view()),
    path("api/earnings/requests/", GetEarningsRequestApiView.as_view()),
    path("api/earnings/request/update/<int:id>/", EarningsRequestApiView.as_view()),
    path("api/bookings/", BookingsApiView.as_view()),
    path("api/bookings/delete/", BookingDeleteApiView.as_view()),
    path("api/booking/update/", BookingUpdateApiView.as_view()),
    path(
        "api/driver/banking/information/<int:id>/",
        AdminDriverBankingInformationApiView.as_view(),
    ),
    path("api/driver/ratings/", DriverRatingsApiView.as_view()),
    path("api/driver/ranking/", DriverRatingsRanking.as_view()),
]
