# Generated by Django 3.2.15 on 2022-10-03 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_id", models.CharField(blank=True, max_length=12, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[(1, "Cash"), (2, "MPESA"), (3, "Card")],
                        default=1,
                        max_length=1,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            (1, "Motorbike"),
                            (2, "Vehicle"),
                            (3, "Van"),
                            (4, "Truck"),
                        ],
                        default=1,
                        max_length=1,
                    ),
                ),
                ("scheduled_date", models.DateTimeField(auto_now_add=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReceiverDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=207)),
                ("phonenumber", models.CharField(max_length=15)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookings.bookings",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            (1, "ELectronics"),
                            (2, "Gift"),
                            (3, "Document"),
                            (4, "Package"),
                            (5, "Food"),
                            (6, "Other"),
                        ],
                        default=1,
                        max_length=1,
                    ),
                ),
                ("image", models.ImageField(upload_to="products")),
                ("instructions", models.TextField(blank=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookings.bookings",
                    ),
                ),
            ],
        ),
    ]
