# Generated by Django 3.2.15 on 2022-10-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="payment_type",
            field=models.CharField(
                choices=[(1, "Cash"), (2, "MPESA"), (3, "Card")],
                default=1,
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="vehicle_type",
            field=models.CharField(
                choices=[(1, "Motorbike"), (2, "Vehicle"), (3, "Van"), (4, "Truck")],
                default=1,
                max_length=1,
            ),
        ),
    ]
