# Generated by Django 3.2.15 on 2022-10-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_auto_20221003_0951"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="formated_address",
            field=models.CharField(blank=True, max_length=207, null=True),
        ),
        migrations.AddField(
            model_name="receiverdetails",
            name="formated_address",
            field=models.CharField(blank=True, max_length=207, null=True),
        ),
    ]
