# Generated by Django 3.2.15 on 2022-10-23 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_alter_products_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receiverdetails",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_receiver",
                to="bookings.bookings",
            ),
        ),
    ]
