# Generated by Django 3.2.15 on 2022-11-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_alter_receiverdetails_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="scheduled_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
