# Generated by Django 3.2.15 on 2022-11-11 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_alter_bookings_scheduled_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="formated_address",
            field=models.CharField(default="Unknown Location", max_length=207),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="latitude",
            field=models.FloatField(default=-1.26856),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="longitude",
            field=models.FloatField(default=36.810808),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="scheduled_date",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="receiverdetails",
            name="formated_address",
            field=models.CharField(default="Unknown Location", max_length=207),
        ),
        migrations.AlterField(
            model_name="receiverdetails",
            name="latitude",
            field=models.FloatField(default=-1.03326),
        ),
        migrations.AlterField(
            model_name="receiverdetails",
            name="longitude",
            field=models.FloatField(default=37.06933),
        ),
    ]
