# Generated by Django 3.2.15 on 2022-11-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0008_auto_20221111_1109"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="latitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="longitude",
            field=models.FloatField(),
        ),
    ]
