# Generated by Django 3.2.15 on 2022-11-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0009_auto_20221111_1111"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="latitude",
            field=models.FloatField(default=-1.26856),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="longitude",
            field=models.FloatField(default=36.810808),
        ),
    ]
