# Generated by Django 3.2.15 on 2022-11-11 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0010_auto_20221111_1114"),
    ]

    operations = []
