# Generated by Django 3.2.15 on 2022-11-11 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0011_auto_20221111_1120"),
    ]

    operations = []
