# Generated by Django 3.2.15 on 2022-11-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0013_auto_20221111_1125"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="formated_address",
            field=models.CharField(default="Unknown Location", max_length=207),
        ),
        migrations.AlterField(
            model_name="receiverdetails",
            name="formated_address",
            field=models.CharField(default="Unknown Location", max_length=207),
        ),
    ]
