# Generated by Django 3.2.15 on 2022-11-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0015_auto_20221111_1142"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="receiverdetails",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="receiverdetails",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
