# Generated by Django 3.2.15 on 2023-04-11 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_alter_products_product_type'),
    ]

    operations = [
    ]
