# Generated by Django 3.2.15 on 2023-04-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_auto_20230411_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookings',
            name='otp',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
