# Generated by Django 3.2.15 on 2023-06-05 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_auto_20230531_1048'),
        ('bookings', '0022_auto_20230424_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='partner',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.partner'),
        ),
    ]
